### ISSUE TITLE
Estou recebendo esse erro

### ISSUE THREAD

**Issue by Delta2525** [ipsBruno/poloniex-trade-bot#12]
C:\Users\pcgames\Desktop\poloniex-trade-bot-master>node tests.js
C:\Users\pcgames\Desktop\poloniex-trade-bot-master\config.js:30
 * M�todo EMA/SMA
    ^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\Users\pcgames\Desktop\poloniex-trade-bot-master\tests.js:2:14)

C:\Users\pcgames\Desktop\poloniex-trade-bot-master>pause
Pressione qualquer tecla para continuar. . .

**Comment by ipsBruno** [comment]
Parece erro de codificação.

Você está dando "git clone repository"?
