### ISSUE TITLE
problema pra rodar no mac

### ISSUE THREAD

**Issue by albertls** [ipsBruno/poloniex-trade-bot#6]
MacBook-Air-de-albert:poloniex-trade-bot-master albert$ node tests.js 
/Users/albert/Downloads/poloniex-trade-bot-master/node_modules/technicalindicators/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { export { sma, SMA } from './moving_averages/SMA';
                                                              ^^^^^^
SyntaxError: Unexpected token export
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:513:28)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/albert/Downloads/poloniex-trade-bot-master/indicators/emasma.js:4:16)
    at Module._compile (module.js:541:32)

o que pode ser ?

**Comment by boydthomson** [comment]
have you installed technicalindicators?
try:
#npm install technicalindicators
